const PRODUCTS = [
  {
    id: 1,
    name: "Pillow 68AX",
    img: "./img/img (13).png",
    price: 100,
    isFavorite: false,
    category: "pillow",
  },
  {
    id: 2,
    name: "Coffee mixer type XX",
    img: "./img/img (25).png",
    price: 230,
    isFavorite: false,
    category: "coffee",
  },
  {
    id: 3,
    name: "iPhone 14 Pro, fake",
    img: "./img/img (3).png",
    price: 1200,
    isFavorite: false,
    category: "phone",
  },
  {
    id: 4,
    name: "Rem pillow long size",
    img: "./img/img (20).png",
    price: 830,
    isFavorite: false,
    category: "anime",
  },
  {
    id: 5,
    name: "watch 789XF",
    img: "./img/img (18).png",
    price: 1500,
    isFavorite: false,
    category: "watch",
  },
  {
    id: 6,
    name: "keyboard 79X NIUS",
    img: "./img/img (6).png",
    price: 100,
    isFavorite: false,
    category: "keyboard",
  },
  {
    id: 7,
    name: "mouse hajiko 7019X",
    img: "./img/img (7).png",
    price: 80,
    isFavorite: false,
    category: "mouse",
  },
  {
    id: 8,
    name: "Coffee mixer hancko 79G",
    img: "./img/img (24).png",
    price: 200,
    isFavorite: false,
    category: "coffee",
  },
  {
    id: 9,
    name: "air force two 792D",
    img: "./img/img (17).png",
    price: 250,
    isFavorite: false,
    category: "shoe",
  },
  {
    id: 10,
    name: "coffee machine 80SDA",
    img: "./img/img (26).png",
    price: 400,
    isFavorite: false,
    category: "coffee",
  },
];
